name: My Workflow

on: [workflow_dispatch]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello world"
        
      - name: Checkout action
        uses: actions/checkout@v4

      - name: Conditional
        if: ${{ 4 % 2 == 0 }}
        run: echo "That worked"
