name: My Workflow

on:
  push:
  workflow_dispatch:
    inputs:
      name:
        description: "Name"
        required: true
        default: "Friend"

      environment:
        description: "Select environment"
        type: choice
        options:
          - dev
          - prod

      testable:
        description: "idk"
        required: false
        default: "false"
        type: boolean

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: |
          echo "Hello, ${{ github.event.inputs.name }}"
          echo "Running on ${{ github.event.inputs.environment }}"

  only-on-prod:
    runs-on: ubuntu-latest
    steps:
      - name: some prod step
        if: github.event.inputs.environment == 'prod'
        run: echo "you're in prod!"
