name: Neo

on: [push]

jobs:
  my-job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18, 20, 22]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Echoer 
        run: echo "OS ${{ matrix.os }} and NodeVersion ${{ matrix.node-version }}"
